# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 511821a13ca16c7ff67951915047b18aaed9501aad01a362583d4c31571606ab66d3656ae22c4661a5a8309a9aef3a1c86de3c8653b35a70f50871e2fe461e5a

test:
  secret_key_base: bf96c79dcaf68a5b6703f6de91cce2a1886d7f20ab1a9063efcc0d09ee52c9c51badb744e836548ec7ac258dd45a2ee60704e3d25b6cd1c905c80f84f26c0e0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
